# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://ezyprocdev.cnjyvc6tlnct.ap-southeast-1.rds.amazonaws.com/ezyprocuredev?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: devadmin
        password: Falcon2050
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    mail:
           host: smtp.mailgun.org
           port: 465
           username: postmaster@ezyprocure.com
           password: c05d17c581c9ab0fa52750a450dc6920
           protocol: smtps
           tls: true
           auth: true
           from: support@ezyprocure.com
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: false
    redis:
        host: ezyprocure-dev.0sc2bt.0001.apse1.cache.amazonaws.com
        port: 6379
        password:
liquibase:
    contexts: dev

ocrservice:
    apiurl: https://ocrdev.ezyprocure.com/ezyprocureocr/api

ezyinventory:
    apiurl: https://ezyinventory-dev-api.ezyprocure.com/api/ezyprocure

# PEPPOL Service
peppolservice:
    apiurl: https://ocrdev.ezyprocure.com/peppolService/api

SFTP:
     port: 22
     host: sftp-stg.ezyprocure.com
     userName: sftpusr
     password: H3rQJDM9?ZEU[dr7tQm5!(@r
     privateKey: /etc/certs/PrivateKey_20180807.ppk

server:
    port: 8080

aws:
    sns:
        region: AP_SOUTHEAST_1
        topicArn: arn:aws:sns:ap-southeast-1:680365993326:app/GCM/ezprocureandroid
        topicOwner: 680365993326
        displayName: EzyProcure
        iosSnsPlatform : APNS
        iosApplicationPlatformARN:
        androidApplicationPlatformARN:

pushconstants:
    baseurl: https://staging.ezyprocure.com
    crossborderBaseUrl: https://cb.ezyprocure.com

xborder:
   activated: true

payment-agent-info:
    logo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/sgebiz-logo-medium.png
    companyName: Singapore E­Business Pte. Ltd.
    addressLine1: JTC LaunchPad @ One-North Block 79,
    addressLine2: Ayer Rajah Crescent,
    addressLine3: "#02-12"
    pin: Singapore - 139955
    gstRegNo: 201409838G
    phone: +65 6200 8021

emailnotification:
    ezyprocureLogo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/ezyprocure-logo-f07898ea-7bd5-47a0-a0c5-4d4d09d1484d.png
    sgebizLogo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/sgebiz-logo-b6934375-7712-4bad-af12-b7ee4bc70499.png
    emailFooterTemplate: footer

axservice:
    url: http://frwebapp2.breadtalk.com:8080/com.InvoiceMulti/rest/Invoice/

kycservice:
    url: https://uat.paymentbureau.sg/ddp/B2BServlet/
    userId: B2BSGEBIZ
    password: RZT839LGH6

ntp:
    iss: cGGypJJNM7bPmqlO9wQky5Mi20KjyF8x
    sub: 100000096228
    aud: NTP
    vasId: 888232
    apiBasePath: https://uat.ntp.gov.sg/api
    jwtApiPath: /oauth/v2
    dataApiPath: /rep/v1
    jwtSignPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wCKtCqoNQS+LblBmEkMdPYNQ1STEgFz0y4HkOfAkfjB36moIFxMFUjlc94iR0LeZ59Fxxal3wAaWtBDLXX+Rrf98BTcy5wpdMIAZkskdBmVmh//MRZypIsNjmfcL9KN8V+78wCK+V3SJX7eL5ZQX7zhYHOJKC9cM+EHDl6hgNRhz5vaJn0JdIwoMjrlAuX2lV0aOtPIew2IvWW8Q2jZBDGghfaiNY/zmQgMvzdQOrN+thAx5t2SjqqdDHbJde3bWXoHpAVaU7gZH9pUDY4dALfgB5E9tHeGI1nk5cXKIdY/dWO6cSX9BBPAvrWunKTlmL7HUf73o1PNLFFHxSBZqwIDAQAB
    jwtSignPrivateKey: MIIEowIBAAKCAQEA0wCKtCqoNQS+LblBmEkMdPYNQ1STEgFz0y4HkOfAkfjB36moIFxMFUjlc94iR0LeZ59Fxxal3wAaWtBDLXX+Rrf98BTcy5wpdMIAZkskdBmVmh//MRZypIsNjmfcL9KN8V+78wCK+V3SJX7eL5ZQX7zhYHOJKC9cM+EHDl6hgNRhz5vaJn0JdIwoMjrlAuX2lV0aOtPIew2IvWW8Q2jZBDGghfaiNY/zmQgMvzdQOrN+thAx5t2SjqqdDHbJde3bWXoHpAVaU7gZH9pUDY4dALfgB5E9tHeGI1nk5cXKIdY/dWO6cSX9BBPAvrWunKTlmL7HUf73o1PNLFFHxSBZqwIDAQABAoIBAB72eGQh0lcdYA7znXWMWqCbLq0Prxk4T1fQ7FlOOMry1vhMPBirkpqY/Nq44QzV+i74h1PEtgh4SmXDI+h65RpZi5D8br4OJ2MzyL06D5pd2r8oLNl2MtKEeTPJd90op52g78Kj9MDNDLZl3JLdGuRBokz2B013Ta9rOQ7ZwhdWTt2tkyJfqzmb24k64P9YUP2QTUzq4X46ZVK+wjasiX1FuLQ8e6dVRHlttwKuIz2pxFSclckfIi0kpAGOBUWEl4pBGIa7RfbvKLU3vxhcHFSBNAP4lUYwBlrD7nNjiINgnYVzwV9A1DpbMcVJ/Hr+bSZf4hDDU0spqLJwcO7Cz7kCgYEA7bn4eP6XgyrvYN2N4eebBcQt0KyCFu5ystqR1GSL8L9H951Q2Lpr9KnQVaRNw+KA54w0wuRmAGscDxY3I9stpNnFrtx/5gO8P+qMwuc9amndEzi2GVYY6oYVuw67u0ycHaOyf7xlTpCfQtDEOkKaO9Pt7m6CZ9n8pGIm8KFF7S8CgYEA4zivNB3yNMVq6plsS0QlNj56CeBNbGpZNCRc5BQ94L2uDy6gF+gz8jEYjwg/gTkNdNdCTrpbX3KsylRthFelieATrVqt7JLtuRhUL9o7K7EWXFX8yFnc5zFX1Fst1lJxIXikgoZ7iahqqnpJrYEfITdHZh1Y1jVxkdPnisbMVEUCgYEA4P9/GKV+KXtdjUSkoQdgRhjjc/mSNroAfR85nth7SqUALHAMsNPgkXSX5jbYE2oxrvWYik057XNy3ySbk6hCjyA+Zb30n3MxnR0VlPLfwfPodeTbFSfT9URrFNxg+mkL6VGiBBv/llhzI/4Le0jGSZHQRDb73ecHo13ylRVO5akCgYB4lM1NkBLH9HhPtUmmC6zfw3oKIbGUtj9Oj3mIREGuMZrcTbcB2OUwQuOwjAT/c6JzfgSfOQBif724xeM0lzqvF2350iR4ZmSnlISgvGQoRJsEN1GllSLIwgPFGvoRQcDtrVNIPUvz+p9Yhvrwi5RUkTxfsXVCgCwb4mN+3w7yLQKBgBLcAdp2vN940l5kEV8GM/8f3Gph1KAylIBDhEJwvYbOXt+Yw0un/kA0Lc4Wm4yZSNeOifWNk3HZPv1vfrGKYl8bFJZ1si822qifJZ9k3bSBNRjIjOx4qpOtbblZHp6sCWzj4GY2c5owtUyAcijfRFArDNziHMzC9jAKZSDCtxlw
    vasPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSIrBTXMvyl9eRL88UnH0iuQuk6wefOV0hkKVx9/oDCRdHk/PCBq9ML9rpXqizEnMI0KC61b8iXkrjPvsLc9fovtM3vAvARIy8lEfBFvqD847x9DAs/kSBKuYWm99u0YOZ+cdUfO74pXpMD9XBPBhgE8RRO4PE04Ub0Wkhv+XAviPUqacOxb8LBNoHojV1O0kyLYXZ1WjwsPERbaBRV5hQXB6z0oMsU7ZnbX6dd/cHAGLHpt6scuy667ZfvoYaph0ihu6lDVCzo/wQaPttPmi2JbMtnNvK8GEXh+b3pjnWpkE7eItUIliRfeP8ur2ROmFgq3E2BeNb2ZooT39EYdpJAgMBAAECggEABzOl8GnHlERG550NTcT7hsFLUVyS0tY7IHsWKDRyEgG577lbHzIApBbMqUkUs8SCPko3zZVYlstCUgopyZHzL0FuO9Ys1xQZwnZlRd8JyARyBDsGP8VlH197mNwkKfwxyd4NJH0GsuLG0OZL4LrDMcLvnxg5gXLyIaGTlon0Ougg3pqKK9/6t9sUQFMJFt9r3k9C4PJq3/DEz/m0Ubn1v+on9NoVIL3+qvRy4+siro7uuHC/ucm5KliN0HilbxHGyeVtxBuZGUjNeMCBURpnTOxzrxtlL6a+OxWI7GZRt4+LHY90hVW5paw4A0y5fSNY26XpaODEaQdD3rTjm4sBXQKBgQDGG5PNJiN4LVHjrLuJwPrbEHTFqs4Zr8V2E/e/jZ5Hqapqo6I82ecTWCINhmmoRPl2o5/ul7SoSda7+bsmasMqcPdkOJ9S0cqfWJxZ9/zQiTlG8cs3or/dx8/Ecx2NEKl5UnIOztBeq8RUeN4+3u5vRW82bifXUc2Y0kZKBGiErQKBgQC81xLljB81OSUm83W1NADNbWNKSHz4UC+5yWcw4p1HEfv2mp5VRubUAjoTWiZqXaGaIiCQ9l6j3neq9H3h5jRm8GYsHgyZwy6b8h524poegCE5KetCdiZ+2MORZGSuIWB/7l64OPhpCEY85tKBNELzHgwr+aaAGLx+GTNpF+XDjQKBgBjJioy4oOeAhCaAjlaGFt0iCfpRjMgZ/hLwHKeTCKLez7vYDYyflxIMjPY0QzQSrUPy5SftQ2VrF7sdXBVKdnDxAYNAsm6iYT/eznFTXgaZpNkDl/G2I1uUjKJ/5MqpswrDDhJcPiYaR85p8STcr+isP2YIEmQWkCr25GSOeKVhAoGAN8Ug/JAMa3CMC1vdiH1qO0EyEK8l0UQFRE453pMete2WxzbUygSdiUF7G1oFfGZYoqevjIBmZOj/2IpKXxvYoAohcqgROpwNONshqiS0NYvLxBEgPMmeBtpHr7nBjjenQ0EH0kpo+sQJ0lStGKFxoFFgcOBTDwO/L1KL/16iacUCgYEAni+o9LUJNJHB4Bj1b1e+aeJ207E0UO7I7oEwW0gCm2vjgJoLD+HWpnZa83YkEkAM/zBE77AN7savDYtW4kvJnfZlxzxWoa1uxYxZ5S3+Qsw5dIEmyEwQeafN/Lt/vngeJmH4bOba/JQJUpn+IG/3OaUEuQ88B6iiN6BLPJ6K+Ns=

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: support@ezyprocure.com
        baseUrl: # keep empty to use the server's default URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: ezyprocure
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512

################################################
##################   NTP   ####################
###############################################
ntpSSOService:
    issuerURL: https://uat.ntp.gov.sg
    audienceToken: z9nPZKBU6UIJi7Lt3fzz

# ===================================================================
# Mail Gun Notify Receivers
# ===================================================================

mailgunNotifyReceivers:
    emailIds: prabu@sgebiz.com,suvarna@sgebiz.com
