# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    jackson:
        serialization:
            indent_output: true
            fail-on-empty-beans: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://ezyprocure-prod.cnjyvc6tlnct.ap-southeast-1.rds.amazonaws.com/ezyprocureprod?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: prodadmin
        password: Rac00n3d
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            minimum-idle: 100
            maximum-pool-size: 300
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    mail:
           host: smtp.mailgun.org
           port: 465
           username: postmaster@ezyprocure.com
           password: c05d17c581c9ab0fa52750a450dc6920
           protocol: smtps
           tls: true
           auth: true
           from: support@ezyprocure.com
    messages:
        cache-seconds: 1
    thymeleaf:
        cache: true
    redis:
        host: ezyprocure-prod.0sc2bt.0001.apse1.cache.amazonaws.com
        port: 6379
        password:
liquibase:
    contexts: prod

# OCR Services
ocrservice:
    apiurl: https://ocr.ezyprocure.com/ezyprocureocr/api

ezyinventory:
    apiurl: https://ezyinventory.ezyprocure.com/api/ezyprocure

# PEPPOL Service
peppolservice:
    apiurl: https://peppol-prod.ezyprocure.com/peppolService/api

SFTP:
     port: 22
     host: 18.136.20.202
     userName: sftp-produsr
     password: H098uyiovwF@7EL56rHH
     privateKey: /etc/certs/PrivateKey_20180807.ppk

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
aws:
    sns:
        region: AP_SOUTHEAST_1
        topicArn: arn:aws:sns:ap-southeast-1:680365993326:app/GCM/ezprocureandroid
        topicOwner: 680365993326
        displayName: EzyProcure
        iosSnsPlatform : APNS
        iosApplicationPlatformARN: arn:aws:sns:ap-southeast-1:680365993326:app/APNS/ezyprocureIosProduction
        androidApplicationPlatformARN:

pushconstants:
    baseurl: https://v2.ezyprocure.com
    crossborderBaseUrl: https://cb.ezyprocure.com

xborder:
    activated: true

payment-agent-info:
    logo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/sgebiz-logo-medium.png
    companyName: Singapore E-Business Pte. Ltd.
    addressLine1: JTC LaunchPad @ One-North Block 79,
    addressLine2: Ayer Rajah Crescent,
    addressLine3: "#02-12"
    pin: Singapore - 139955
    gstRegNo: 201409838G
    phone: +65 6200 8021

emailnotification:
    ezyprocureLogo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/ezyprocure-logo-f07898ea-7bd5-47a0-a0c5-4d4d09d1484d.png
    sgebizLogo: https://s3-ap-southeast-1.amazonaws.com/ezyprocure-static/sgebiz-logo-b6934375-7712-4bad-af12-b7ee4bc70499.png
    emailFooterTemplate: footer

axservice:
    url: http://frwebapp2.breadtalk.com:8080/com.InvoiceMulti/rest/Invoice/

kycservice:
    url: https://www.sccb.sg/API/B2BServlet/
    userId: LOUIS
    password: 1XKKXRLH

ntp:
    iss: 8eDx1idKs0VkXAawHu98Dt72EFA3PJ0U
    sub: 100000048379
    aud: NTP
    vasId: 11603
    apiBasePath: https://www.ntp.gov.sg/api
    jwtApiPath: /oauth/v2
    dataApiPath: /rep/v1
    jwtSignPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0wCKtCqoNQS+LblBmEkMdPYNQ1STEgFz0y4HkOfAkfjB36moIFxMFUjlc94iR0LeZ59Fxxal3wAaWtBDLXX+Rrf98BTcy5wpdMIAZkskdBmVmh//MRZypIsNjmfcL9KN8V+78wCK+V3SJX7eL5ZQX7zhYHOJKC9cM+EHDl6hgNRhz5vaJn0JdIwoMjrlAuX2lV0aOtPIew2IvWW8Q2jZBDGghfaiNY/zmQgMvzdQOrN+thAx5t2SjqqdDHbJde3bWXoHpAVaU7gZH9pUDY4dALfgB5E9tHeGI1nk5cXKIdY/dWO6cSX9BBPAvrWunKTlmL7HUf73o1PNLFFHxSBZqwIDAQAB
    jwtSignPrivateKey: MIIEowIBAAKCAQEA0wCKtCqoNQS+LblBmEkMdPYNQ1STEgFz0y4HkOfAkfjB36moIFxMFUjlc94iR0LeZ59Fxxal3wAaWtBDLXX+Rrf98BTcy5wpdMIAZkskdBmVmh//MRZypIsNjmfcL9KN8V+78wCK+V3SJX7eL5ZQX7zhYHOJKC9cM+EHDl6hgNRhz5vaJn0JdIwoMjrlAuX2lV0aOtPIew2IvWW8Q2jZBDGghfaiNY/zmQgMvzdQOrN+thAx5t2SjqqdDHbJde3bWXoHpAVaU7gZH9pUDY4dALfgB5E9tHeGI1nk5cXKIdY/dWO6cSX9BBPAvrWunKTlmL7HUf73o1PNLFFHxSBZqwIDAQABAoIBAB72eGQh0lcdYA7znXWMWqCbLq0Prxk4T1fQ7FlOOMry1vhMPBirkpqY/Nq44QzV+i74h1PEtgh4SmXDI+h65RpZi5D8br4OJ2MzyL06D5pd2r8oLNl2MtKEeTPJd90op52g78Kj9MDNDLZl3JLdGuRBokz2B013Ta9rOQ7ZwhdWTt2tkyJfqzmb24k64P9YUP2QTUzq4X46ZVK+wjasiX1FuLQ8e6dVRHlttwKuIz2pxFSclckfIi0kpAGOBUWEl4pBGIa7RfbvKLU3vxhcHFSBNAP4lUYwBlrD7nNjiINgnYVzwV9A1DpbMcVJ/Hr+bSZf4hDDU0spqLJwcO7Cz7kCgYEA7bn4eP6XgyrvYN2N4eebBcQt0KyCFu5ystqR1GSL8L9H951Q2Lpr9KnQVaRNw+KA54w0wuRmAGscDxY3I9stpNnFrtx/5gO8P+qMwuc9amndEzi2GVYY6oYVuw67u0ycHaOyf7xlTpCfQtDEOkKaO9Pt7m6CZ9n8pGIm8KFF7S8CgYEA4zivNB3yNMVq6plsS0QlNj56CeBNbGpZNCRc5BQ94L2uDy6gF+gz8jEYjwg/gTkNdNdCTrpbX3KsylRthFelieATrVqt7JLtuRhUL9o7K7EWXFX8yFnc5zFX1Fst1lJxIXikgoZ7iahqqnpJrYEfITdHZh1Y1jVxkdPnisbMVEUCgYEA4P9/GKV+KXtdjUSkoQdgRhjjc/mSNroAfR85nth7SqUALHAMsNPgkXSX5jbYE2oxrvWYik057XNy3ySbk6hCjyA+Zb30n3MxnR0VlPLfwfPodeTbFSfT9URrFNxg+mkL6VGiBBv/llhzI/4Le0jGSZHQRDb73ecHo13ylRVO5akCgYB4lM1NkBLH9HhPtUmmC6zfw3oKIbGUtj9Oj3mIREGuMZrcTbcB2OUwQuOwjAT/c6JzfgSfOQBif724xeM0lzqvF2350iR4ZmSnlISgvGQoRJsEN1GllSLIwgPFGvoRQcDtrVNIPUvz+p9Yhvrwi5RUkTxfsXVCgCwb4mN+3w7yLQKBgBLcAdp2vN940l5kEV8GM/8f3Gph1KAylIBDhEJwvYbOXt+Yw0un/kA0Lc4Wm4yZSNeOifWNk3HZPv1vfrGKYl8bFJZ1si822qifJZ9k3bSBNRjIjOx4qpOtbblZHp6sCWzj4GY2c5owtUyAcijfRFArDNziHMzC9jAKZSDCtxlw
    vasPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDsyv5Ys+d+azLmsNSRTZXFW3AT0KZ7s7xJKwcK1jPNon3p9eO0oFQPWwJPHp9jYUi83+L+++dL9yI0D3/la7vnctMuX3C7zTqNipg+xYLLFIvo+mWvzNbGAKZN+yE2unZgTv2fJw2dirdScBOZU48gOdYdZpO60U0sG5iVfUenPRvtNS8+8vwDw4zq4S8jo/9ZRXtfwLIA1oju6nKXxakHbHrPV0cAUMTeDgpEEmv4nxo4FdZVkUrchP7kDxy7bIoc2kzMuQI1qz2/jWThCpfWS2UgPIslkZhvzApAtqCPJZyBzNyXzC8Lb+V/04bEnugzzhkcyfo6JUFpqSmSHjEBAgMBAAECggEAJPp8ZujNZXojLFCAGaLmmTfy1D1Yymeip0B/bItP8rSF+lPqd+ozxmQdg7KSDIiEPe6uucgn8j6JSl0DSZYd9YKChTLlXYaqtrDmnqLkjodKZBs6Zw5Tmf8++V2W7b+HvfmH9OM55pjjkQ2smdypNMyjadr7hgiqhxFWLj4uwuhku8Fxfv6Ht021ij3cj8IYf764O12y8FJE4qW4HvUprV/sdQ5fGaigMLH6UpPOreDZHZTm0VHbUHp9Gi2mI3mPGL+QlegTRV62nPasEpRPX7D8+icU3tNAB4ucpzFf2AX3Z9P/35UZvVg+6hg0VRUFOQdB2/+BE7dM7T2yYRfRiwKBgQD6SRgAM1Nf78W+ucifd63mQsTEdhVDBGnhQQyNYOYAntW/s4vm9EER13yicXLbcZirkF7Ef2G97PhcsmJjoJuVmhK4PokD25cYq3EHsqhC/VQm8/CfAmiirrXKDzK7Ged+VoSYegweVoohK6RCReDJcaWfbEMmgVzq5JrplRO4VwKBgQDyMwlN5qpcNd++QmuSvtFIx64Tsq3qLTui0O7ZB0QYjitAmxRfe8pqd1Y8X37nMcDuvPniEWaTpLoBhBzZsbRwIc+dH4yNJHZ5G1Uhji0N0mQFptLLVaWH0BQ1CtTNJcEz2S2VjtL62KRgFDjpfTIMv16epyzQduzd1DHw7R1qZwKBgFOpqUcv4PfZu30ktyZvKAcnXITbgAH18LqmNt7vfBLLBWJeTy61iSbApF3clGs8Tq9SxArlFbQaCW9bBb6NylQ4u3cxGDXc6mYJsO/EzbAO5FldA5rzgCyZQBU5/VhDsXkuzIX3jiN6BBRQdUjd+OT9g0KGOvAdIAU4w3u/JGdjAoGBAKc2MRBFVgx/bU9vj9EqSFcU9MvIqmVogSmxUZUofQzu6lGaP4CEeIT0iub3jyeSo/6vHV3EYatBKOHvEfQBye84iJuTsnenWtvV0PpvrA9E16VHPXUAVl3jfG/6YFyZ2j8vi1cb2fExLJrgm0IoGyvN20dxZ3EtCe9Elo4dRhe1AoGBANuU2EoILSKkrK34DfxLN0WG8SXFMVXU/fH1yuJh2ocqCTw4dHFODP/34wTdH0UcyLZhOzokAmXRGdQ6qsyImB8W0wAVTFhukuCuIHjvA6YIzemhVdXrCjMezvBCMVQrBzongh8IaXbqXMx04VCA9DoLShwRxl2p2pNLvu+F2ArA

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        authentication:
            jwt:
                secret: ef23914cc729d0084f57f83b0abe169fbc7d4ddb
                # Token is valid 24 hours
                tokenValidityInSeconds: 86400
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: support@ezyprocure.com
        baseUrl: # keep empty to use the server's default URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: ezyprocure
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512

################################################
##################   NTP   ####################
###############################################
ntpSSOService:
    issuerURL: https://www.ntp.gov.sg
    audienceToken: bjXYMxc3ZmJ5qNq2BBc8

# ===================================================================
# Mail Gun Notify Receivers
# ===================================================================

mailgunNotifyReceivers:
    emailIds: mailgun_notify@ezyprocure.com
